### ISSUE TITLE
Some questions about Table 4.

### ISSUE THREAD

**Issue by wu39848** [hithqd/UniM-OV3D#1]
Hi, thanks for your great work!I found that in Table 4 of this paper, the first row indicates that when the network does not include any components, the hiou values for B15/N4 and B12/N7 are 46.2 and 43.5, respectively. However, as far as I know, it is challenging to achieve significant performance on the novel class during the training phase when labels are not assigned to points in the novel category. Therefore, I would like to know how you managed to accomplish this.

**Comment by hithqd** [comment]
Hi,

Thank you for your interest in our work. The base setting is modified from PLA. As we describe in the Ablation Studies part, the default setting is to only use three modalities of image, text and point cloud. The 3D point cloud encoder uses sparse convolutional UNet. The point captions come from corresponding image captions, and we use CLIP as the image and text encoder. And the results in the base setting are all based on this.

**Comment by wu39848** [comment]
Thank you for your timely response and the great work！
